/**
 * generateRevision.handler.js — BUILDER_GENERATE_REVISION.
 *
 * Stages:
 *   VALIDATE_PROJECT → LOAD_TEMPLATE → VERIFY_TEMPLATE → CREATE_WORKSPACE →
 *   NORMALIZE_INPUT → GENERATE → APPLY_CONTENT → SCAN_OUTPUT →
 *   CREATE_ARTIFACT → WRITE_REVISION → COMPLETE
 *
 * Uses the Template AI Engine's content application (and OpenAI tailoring when
 * configured) — never mutates the original template; everything happens in a
 * job-specific workspace that becomes an immutable artifact on success.
 *
 * Honesty rule: when no AI provider is configured the revision is generated by
 * deterministic content merge and generationModel records exactly that — an
 * unchanged template is never presented as successful AI output.
 */

import { existsSync } from 'node:fs';
import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import * as repo from '../../../repositories/builder.repository.js';
import { loadTemplate } from '../../generation/templateLoader.js';
import { validateWorkspace } from '../../generation/outputValidator.js';
import { workspaceRootDir, writeArtifact } from '../../generation/artifactWriter.js';
import { applyQuestionnaireDataToGeneratedSource } from '../../../glondia-engines/02-TEMPLATE-AI-ENGINE/02-TEMPLATE-SOURCE-MOUNTAIN/templateSource.stage.js';

function permanent(code, message, details = undefined) {
  const err = new Error(message);
  err.code = code;
  err.retryable = false;
  err.details = details;
  return err;
}

function flattenAnswers(answerSheet = {}, planSnapshot = {}) {
  const sheet = answerSheet?.data ?? answerSheet ?? {};
  const plan = planSnapshot?.data ?? planSnapshot ?? {};
  const brief = plan.brief || {};
  return {
    businessName: sheet.businessName || brief.businessName || brief.name || '',
    industry: sheet.industry || brief.industry || '',
    description: sheet.description || brief.description || '',
    offer: sheet.offer || sheet.description || brief.description || '',
    audience: sheet.audience || brief.audience || '',
    tone: sheet.tone || plan.style?.tone || '',
    colors: sheet.colors || plan.style?.colors || '',
    contactEmail: sheet.contactEmail || brief.contactEmail || '',
    contactPhone: sheet.contactPhone || brief.contactPhone || '',
    contactAddress: sheet.contactAddress || brief.contactAddress || '',
    pages: Array.isArray(sheet.pages) ? sheet.pages.map((p) => p?.title || p).filter(Boolean) : [],
    answerSheet: sheet,
  };
}

async function copyTemplateToWorkspace(template, workspaceDir) {
  await rm(workspaceDir, { recursive: true, force: true });
  await mkdir(workspaceDir, { recursive: true });
  for (const file of template.files) {
    if (file.path === 'template.json') continue;
    const target = join(workspaceDir, ...file.path.split('/'));
    await mkdir(dirname(target), { recursive: true });
    await copyFile(join(template.dir, ...file.path.split('/')), target);
  }
}

async function maybeTailorWithAi(workspaceDir, answers, ctx) {
  if (!process.env.OPENAI_API_KEY) {
    return { model: 'template-content-merge:v1', mode: 'deterministic', usage: {} };
  }
  const entryPath = join(workspaceDir, 'index.html');
  if (!existsSync(entryPath)) {
    return { model: 'template-content-merge:v1', mode: 'deterministic', usage: {} };
  }
  const { tailorHtmlTemplate } = await import(
    '../../../glondia-engines/02-TEMPLATE-AI-ENGINE/04-AI-REFINEMENT-MOUNTAIN/openaiTailor.stage.js'
  );
  const html = await readFile(entryPath, 'utf8');
  try {
    const tailored = await tailorHtmlTemplate(html, answers);
    if (tailored && tailored.length > 100) {
      await writeFile(entryPath, tailored, 'utf8');
    }
    const model = process.env.OPENAI_MODEL || 'gpt-4o-mini';
    return { model, mode: 'ai_tailored', usage: { provider: 'openai', model } };
  } catch (err) {
    // Provider errors are retryable (429/5xx/network) — let the worker decide.
    const status = Number(err.status || 0);
    if (status === 429) err.code = 'AI_RATE_LIMITED';
    else if (status >= 500 || !status) err.code = err.code || 'AI_PROVIDER_ERROR';
    else err.retryable = false; // 4xx other than 429 will not fix itself
    await ctx.emit('AI tailoring failed.', { errorCode: err.code || 'AI_ERROR' }, 'warn');
    throw err;
  }
}

export async function run(ctx) {
  const { job } = ctx;
  const payload = job.payload?.data ?? job.payload ?? {};

  await ctx.setStage('VALIDATE_PROJECT');
  const project = await repo.getProjectById(job.projectId);
  if (!project) throw permanent('BUILDER_PROJECT_MISSING', 'Project no longer exists.');
  const revision = await repo.getRevisionById(job.revisionId);
  if (!revision) throw permanent('BUILDER_REVISION_MISSING', 'Revision no longer exists.');
  if (revision.status === 'APPROVED') {
    throw permanent('BUILDER_REVISION_IMMUTABLE', 'Approved revisions are immutable.');
  }
  if (project.sourceType !== 'template' || !project.templateId) {
    throw permanent('BUILDER_SOURCE_UNSUPPORTED', 'Generation currently supports template projects only.');
  }

  // GENERATION_QUEUED → GENERATING (idempotent across retries).
  if (project.status === 'GENERATION_QUEUED') {
    await repo.transitionProject({
      projectId: project.id, from: 'GENERATION_QUEUED', to: 'GENERATING',
      actorType: 'worker', actorId: ctx.workerId, reason: 'generation_started', jobId: job.id,
    });
  } else if (project.status !== 'GENERATING') {
    throw permanent('BUILDER_ILLEGAL_TRANSITION', `Project is ${project.status}; expected GENERATION_QUEUED or GENERATING.`);
  }
  await repo.markRevisionGenerating(job.revisionId);

  await ctx.setStage('LOAD_TEMPLATE');
  const template = await loadTemplate(project.templateId);

  await ctx.setStage('VERIFY_TEMPLATE');
  if (project.templateManifestHash && template.manifestHash !== project.templateManifestHash) {
    throw permanent('TEMPLATE_CHECKSUM_MISMATCH',
      'The template changed since this project pinned it. Re-create the project or re-pin the template.', {
        pinned: project.templateManifestHash,
        actual: template.manifestHash,
      });
  }

  await ctx.setStage('CREATE_WORKSPACE');
  const workspaceDir = join(workspaceRootDir(), job.id);
  await copyTemplateToWorkspace(template, workspaceDir);

  try {
    await ctx.setStage('NORMALIZE_INPUT');
    const answers = flattenAnswers(revision.answerSheet, revision.planSnapshot);
    if (!answers.businessName) {
      throw permanent('BUILDER_ANSWER_SHEET_INVALID', 'The answer sheet is missing a business name.');
    }

    await ctx.setStage('GENERATE');
    await ctx.renewLease();
    const generation = await maybeTailorWithAi(workspaceDir, answers, ctx);

    await ctx.setStage('APPLY_CONTENT');
    await applyQuestionnaireDataToGeneratedSource(workspaceDir, {
      ...answers,
      siteName: answers.businessName,
      slug: project.slug,
      templateId: project.templateId,
    }, {
      site: { siteId: project.id, userId: project.userId },
      template: template.metadata,
      slug: project.slug,
      sourceReference: `templates/${project.templateId}`,
    });

    await ctx.setStage('SCAN_OUTPUT');
    await ctx.renewLease();
    const validation = await validateWorkspace(workspaceDir);
    if (!validation.ok) {
      throw permanent('BUILDER_OUTPUT_UNSAFE', 'Generated output failed validation.', {
        errors: validation.errors.map((e) => ({ code: e.code, file: e.file, detail: e.detail })),
      });
    }

    await ctx.setStage('CREATE_ARTIFACT');
    const { artifactLocation, checksum, manifest } = await writeArtifact({
      workspaceDir,
      revisionId: job.revisionId,
      projectId: project.id,
      template: {
        templateId: project.templateId,
        templateVersion: project.templateVersion,
        templateSourceCommit: project.templateSourceCommit,
        templateManifestHash: project.templateManifestHash,
      },
      planSnapshot: revision.planSnapshot,
      answerSheet: revision.answerSheet,
      validationReport: validation,
      generation: { model: generation.model, mode: generation.mode },
    });

    await ctx.setStage('WRITE_REVISION');
    const marked = await repo.markRevisionReady({
      revisionId: job.revisionId,
      artifactLocation,
      artifactChecksum: checksum,
      sourceCommit: project.templateSourceCommit,
      generatedSite: {
        fileCount: manifest.fileCount,
        totalBytes: manifest.totalBytes,
        entry: 'index.html',
        mode: generation.mode,
      },
      generationModel: generation.model,
      generationUsage: generation.usage,
      validation,
    });
    if (!marked) throw permanent('BUILDER_REVISION_IMMUTABLE', 'Revision could not be updated (approved revisions are immutable).');

    await repo.recordAiUsageEvent({
      userId: project.userId,
      projectId: project.id,
      jobId: job.id,
      provider: generation.mode === 'ai_tailored' ? 'openai' : 'internal',
      model: generation.model,
      operation: 'builder_generate_revision',
      status: 'succeeded',
    });

    await repo.transitionProject({
      projectId: project.id, from: 'GENERATING', to: 'PREVIEW_READY',
      actorType: 'worker', actorId: ctx.workerId, reason: 'generation_succeeded', jobId: job.id,
    });

    return {
      revisionId: job.revisionId,
      artifactChecksum: checksum,
      fileCount: manifest.fileCount,
      generationMode: generation.mode,
    };
  } finally {
    await rm(workspaceDir, { recursive: true, force: true }).catch(() => {});
  }
}

/** Permanent failure: revision FAILED, project GENERATION_FAILED. */
export async function onPermanentFailure(ctx, error) {
  const { job } = ctx;
  await repo.markRevisionFailed({
    revisionId: job.revisionId,
    validation: { ok: false, errorCode: error.code || 'GENERATION_FAILED', errors: error.details?.errors || [] },
  });
  const project = await repo.getProjectById(job.projectId);
  if (project && ['GENERATING', 'GENERATION_QUEUED'].includes(project.status)) {
    await repo.transitionProject({
      projectId: job.projectId, from: project.status, to: 'GENERATION_FAILED',
      actorType: 'worker', actorId: ctx.workerId, reason: error.code || 'generation_failed', jobId: job.id,
    });
  }
}
